/*
 * This source file was generated by the Gradle 'init' task
 */
package trig3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        TriangleBoard board = new TriangleBoard(5);
        board.printBoard();
    }
}
